# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_client.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1123, 592)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resource/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 651, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_upload = QtWidgets.QPushButton(self.groupBox)
        self.btn_upload.setGeometry(QtCore.QRect(10, 0, 40, 40))
        self.btn_upload.setStyleSheet("border-image: url(:/icons/resource/ppt.png);")
        self.btn_upload.setText("")
        self.btn_upload.setIconSize(QtCore.QSize(48, 48))
        self.btn_upload.setObjectName("btn_upload")
        self.btn_openpath = QtWidgets.QPushButton(self.groupBox)
        self.btn_openpath.setEnabled(True)
        self.btn_openpath.setGeometry(QtCore.QRect(70, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_openpath.sizePolicy().hasHeightForWidth())
        self.btn_openpath.setSizePolicy(sizePolicy)
        self.btn_openpath.setStyleSheet("border-image: url(:/icons/resource/scrip.png);")
        self.btn_openpath.setText("")
        self.btn_openpath.setIconSize(QtCore.QSize(48, 48))
        self.btn_openpath.setObjectName("btn_openpath")
        self.btn_close_camera = QtWidgets.QPushButton(self.groupBox)
        self.btn_close_camera.setEnabled(True)
        self.btn_close_camera.setGeometry(QtCore.QRect(600, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_camera.sizePolicy().hasHeightForWidth())
        self.btn_close_camera.setSizePolicy(sizePolicy)
        self.btn_close_camera.setStyleSheet("border-image: url(:/icons/resource/close_camera.png);")
        self.btn_close_camera.setText("")
        self.btn_close_camera.setIconSize(QtCore.QSize(48, 48))
        self.btn_close_camera.setObjectName("btn_close_camera")
        self.btn_open_camera = QtWidgets.QPushButton(self.groupBox)
        self.btn_open_camera.setEnabled(True)
        self.btn_open_camera.setGeometry(QtCore.QRect(540, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_camera.sizePolicy().hasHeightForWidth())
        self.btn_open_camera.setSizePolicy(sizePolicy)
        self.btn_open_camera.setStyleSheet("border-image: url(:/icons/resource/open_camera.png);")
        self.btn_open_camera.setText("")
        self.btn_open_camera.setIconSize(QtCore.QSize(48, 48))
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(200, 10, 51, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(280, 10, 61, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(370, 10, 71, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.log_view = QtWidgets.QTextBrowser(Dialog)
        self.log_view.setGeometry(QtCore.QRect(680, 390, 432, 191))
        self.log_view.setAutoFillBackground(True)
        self.log_view.setObjectName("log_view")
        self.camera_view = QtWidgets.QLabel(Dialog)
        self.camera_view.setGeometry(QtCore.QRect(680, 10, 432, 368))
        self.camera_view.setStyleSheet("border-image: url(:/icons/resource/openpose.png);")
        self.camera_view.setText("")
        self.camera_view.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.camera_view.setObjectName("camera_view")
        self.ppt_view = QtWidgets.QLabel(Dialog)
        self.ppt_view.setGeometry(QtCore.QRect(10, 100, 656, 368))
        font = QtGui.QFont()
        font.setFamily("Hiragino Sans GB")
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ppt_view.setFont(font)
        self.ppt_view.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ppt_view.setAutoFillBackground(False)
        self.ppt_view.setStyleSheet("border-image: url(:/icons/resource/loading.png)")
        self.ppt_view.setTextFormat(QtCore.Qt.AutoText)
        self.ppt_view.setScaledContents(True)
        self.ppt_view.setAlignment(QtCore.Qt.AlignCenter)
        self.ppt_view.setObjectName("ppt_view")
        self.groupControl = QtWidgets.QGroupBox(Dialog)
        self.groupControl.setGeometry(QtCore.QRect(10, 480, 661, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupControl.sizePolicy().hasHeightForWidth())
        self.groupControl.setSizePolicy(sizePolicy)
        self.groupControl.setTitle("")
        self.groupControl.setObjectName("groupControl")
        self.btn_prev = QtWidgets.QPushButton(self.groupControl)
        self.btn_prev.setGeometry(QtCore.QRect(20, 50, 40, 40))
        self.btn_prev.setAutoFillBackground(False)
        self.btn_prev.setStyleSheet("")
        self.btn_prev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resource/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon1)
        self.btn_prev.setIconSize(QtCore.QSize(32, 32))
        self.btn_prev.setObjectName("btn_prev")
        self.btn_play = QtWidgets.QPushButton(self.groupControl)
        self.btn_play.setGeometry(QtCore.QRect(80, 50, 40, 40))
        self.btn_play.setAutoFillBackground(False)
        self.btn_play.setStyleSheet("")
        self.btn_play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resource/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon2)
        self.btn_play.setIconSize(QtCore.QSize(32, 32))
        self.btn_play.setObjectName("btn_play")
        self.btn_next = QtWidgets.QPushButton(self.groupControl)
        self.btn_next.setGeometry(QtCore.QRect(140, 50, 40, 40))
        self.btn_next.setStyleSheet("")
        self.btn_next.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resource/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon3)
        self.btn_next.setIconSize(QtCore.QSize(32, 32))
        self.btn_next.setObjectName("btn_next")
        self.btn_expand = QtWidgets.QPushButton(self.groupControl)
        self.btn_expand.setGeometry(QtCore.QRect(200, 50, 40, 40))
        self.btn_expand.setStyleSheet("")
        self.btn_expand.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resource/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_expand.setIcon(icon4)
        self.btn_expand.setIconSize(QtCore.QSize(32, 32))
        self.btn_expand.setObjectName("btn_expand")
        self.subtitle_view = QtWidgets.QLabel(self.groupControl)
        self.subtitle_view.setGeometry(QtCore.QRect(20, 10, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.subtitle_view.setFont(font)
        self.subtitle_view.setText("")
        self.subtitle_view.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle_view.setObjectName("subtitle_view")
        self.progress_bar = QtWidgets.QSlider(self.groupControl)
        self.progress_bar.setGeometry(QtCore.QRect(259, 60, 381, 22))
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setObjectName("progress_bar")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 651, 41))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_connect = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_connect.setGeometry(QtCore.QRect(280, 10, 91, 25))
        self.btn_connect.setObjectName("btn_connect")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 31, 25))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 25))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 10, 41, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 101, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.btn_connect_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_connect_2.setGeometry(QtCore.QRect(380, 10, 91, 25))
        self.btn_connect_2.setObjectName("btn_connect_2")
        self.btn_clear_log = QtWidgets.QToolButton(Dialog)
        self.btn_clear_log.setGeometry(QtCore.QRect(1039, 400, 61, 21))
        self.btn_clear_log.setAutoFillBackground(True)
        self.btn_clear_log.setIconSize(QtCore.QSize(40, 20))
        self.btn_clear_log.setObjectName("btn_clear_log")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "机器人客户端V1.0"))
        self.groupBox.setStatusTip(_translate("Dialog", "上传PPT"))
        self.radioButton.setText(_translate("Dialog", "中文"))
        self.radioButton_2.setText(_translate("Dialog", "日本語"))
        self.radioButton_3.setText(_translate("Dialog", "English"))
        self.ppt_view.setText(_translate("Dialog", "A1-Project 授课机器人客户端"))
        self.btn_connect.setText(_translate("Dialog", "连接"))
        self.label_2.setText(_translate("Dialog", "端口"))
        self.label.setText(_translate("Dialog", "服务端IP"))
        self.lineEdit_2.setText(_translate("Dialog", "8888"))
        self.lineEdit.setText(_translate("Dialog", "192.168.1.160"))
        self.btn_connect_2.setText(_translate("Dialog", "断开"))
        self.btn_clear_log.setText(_translate("Dialog", "CLS"))

import icons_rc
